---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: ${GCP_CREDENTIALS_PROJECT}
  credentials:
    source: Secret
    secretRef:
      name: gcp-secret
      key: credentials
      namespace: crossplane-system
