name: Build BACK Stack Bead Porter PKG

on:
  push:
    branches:
      - main
    paths:
      - 'porter/**'
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PORTER_VERSION: v1.0.16
  PORTER_MIXIN_DOCKER_VERSION: v1.0.2
  PORTER_MIXIN_KUBERNETES_VERSION: v1.0.3
  PORTER_MIXIN_HELM_VERSION: v1.0.1
  PORTER_MIXIN_HELM_URL: https://mchorfa.github.io/porter-helm3/atom.xml

jobs:
  porter:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag
        run: echo "VERSION_TAG=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
        id: tag

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install porter
        run: |
          curl -L https://cdn.porter.sh/$PORTER_VERSION/install-linux.sh | bash
          echo "/home/runner/.porter" >> $GITHUB_PATH

      - name: Install porter mixins
        run: |
          porter mixin install docker --version $PORTER_MIXIN_DOCKER_VERSION && porter mixin install kubernetes --version $PORTER_MIXIN_KUBERNETES_VERSION && porter mixin install helm3 --feed-url $PORTER_MIXIN_HELM_URL --version $PORTER_MIXIN_HELM_VERSION

      - name: Lint the bundle
        run: |
          porter bundle lint -f porter/porter.yaml

      - name: Build porter bundle
        run: |
          porter build --dir porter --name ${{ env.IMAGE_NAME }}-porter --version v0.1.0+${{ steps.tag.outputs.VERSION_TAG }}

      - name: Push ${{ steps.tag.outputs.VERSION_TAG }} & latest
        run: |
          porter publish --dir porter
          porter publish --dir porter --tag latest --force
